sudo: false
notifications:
  email: false
language: python
env:
  global:
    - CPLUS_INCLUDE_PATH=$HOME/gdal/include
    - C_INCLUDE_PATH=$HOME/gdal/include
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/gdal/lib
    - PATH=$PATH:$HOME/gdal/bin
matrix:
  include:
    - env: TOX_ENV=py27
    - python: 3.5
      env: TOX_ENV=py35
    - env: TOX_ENV=coveralls
  allow_failures:
    - env: TOX_ENV=py35
cache:
  directories:
    - $HOME/gdal
services:
  - redis-server
before_install:
  - bash install-gdal.sh
before_script:
  - echo "Using gdal version $(gdal-config --version)"
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
