notifications:
  email: false
  slack:
    secure: yExnscxSnK6cWdzrtvO6b2t1Z0eXt8nxl9kzSzdzQrf7kYDm4qSHopV7XqvLqeOs/dEKSVfIBAH2wm4VzzrQ9S8Eyg+v0xbGoQnkRlmnaVYmCvJPVrUtHOr7UzQXT0b4ai6Bkq5Btf5xZEnyyVSF3tiOaOjBejzBUKRbpXeTW20=
language: python
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgdal1h libgdal1-dev gdal-bin
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
after_success:
  - tox -e coveralls
