sudo: required
dist: trusty
notifications:
  email: false
language: python
env:
  global:
    - CPLUS_INCLUDE_PATH=/usr/include/gdal
    - C_INCLUDE_PATH=/usr/include/gdal
  matrix:
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=coveralls
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update -q
  - sudo apt-get install -y libgdal1h libgdal1-dev gdal-bin
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
