sudo: false
notifications:
  email: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -r requirements-py26.txt; fi"
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script: coverage run --source=kepler manage.py test
after_success: coveralls
