sudo: false
notifications:
  email: false
language: python
addons:
  apt:
    packages:
      - libgdal1h
      - libgdal1-dev
      - gdal-bin
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
after_success:
  - tox -e coveralls
