"""empty message

Revision ID: 27218bf42392
Revises: 75112b127f4
Create Date: 2016-07-08 13:46:27.193395

"""

# revision identifiers, used by Alembic.
revision = '27218bf42392'
down_revision = '75112b127f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('import_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'import_url')
    ### end Alembic commands ###
