"""empty message

Revision ID: 3b169d3d649c
Revises: 27218bf42392
Create Date: 2016-07-18 09:27:44.545568

"""

# revision identifiers, used by Alembic.
revision = '3b169d3d649c'
down_revision = '27218bf42392'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('error_msg', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'error_msg')
    ### end Alembic commands ###
