"""empty message

Revision ID: 48d455554131
Revises: 3b169d3d649c
Create Date: 2016-07-28 10:14:04.100238

"""

# revision identifiers, used by Alembic.
revision = '48d455554131'
down_revision = '3b169d3d649c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('record', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'record')
    ### end Alembic commands ###
